sonar.projectKey=zoologistExplorer02
sonar.projectName=cTeacher
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.js
sonar.exclusions=node_modules/**,dist/**,.vite/**,.vue/**,coverage/**,playwright-report/**,test-results/**,reports/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info